//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framewoek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivary
    {
        public int Id { get; set; }
        public string DriverName { get; set; }
        public string CarType { get; set; }
        public int MoskovyanKFCId { get; set; }
        public int KomitasKFCId { get; set; }
    
        public virtual MoskovyanKFC MoskovyanKFC { get; set; }
        public virtual KomitasKFC KomitasKFC { get; set; }
    }
}
