//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framewoek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DerjavadbContainer : DbContext
    {
        public DerjavadbContainer()
            : base("name=DerjavadbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Derjava> Derjavas { get; set; }
        public virtual DbSet<YerevanMallKFC> YerevanMallKFCs { get; set; }
        public virtual DbSet<MoskovyanKFC> MoskovyanKFCs { get; set; }
        public virtual DbSet<RIOKFC> RIOKFCs { get; set; }
        public virtual DbSet<DalmaMallKFC> DalmaMallKFCs { get; set; }
        public virtual DbSet<Delivary> Delivaries { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<KomitasKFC> KomitasKFCs { get; set; }
    }
}
