//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framewoek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.YerevanMallKFC1 = new HashSet<YerevanMallKFC>();
            this.DalmaMallKFCs = new HashSet<DalmaMallKFC>();
            this.MoskovyanKFCs = new HashSet<MoskovyanKFC>();
            this.RIOKFCs = new HashSet<RIOKFC>();
            this.RIOKFC = new HashSet<RIOKFC>();
            this.KomitasKFCs = new HashSet<KomitasKFC>();
        }
    
        public int Id { get; set; }
        public string DriverName { get; set; }
        public string CarType { get; set; }
        public int YerevanMallKFCId { get; set; }
    
        public virtual YerevanMallKFC YerevanMallKFC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YerevanMallKFC> YerevanMallKFC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DalmaMallKFC> DalmaMallKFCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoskovyanKFC> MoskovyanKFCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIOKFC> RIOKFCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIOKFC> RIOKFC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KomitasKFC> KomitasKFCs { get; set; }
    }
}
